In [16]:
import sys
sys.path.append("C:/Users/user/Desktop/Github/hex.github.io/Game/AI/TreeSearch/")
sys.path.append("C:/Users/user/Desktop/Github/hex.github.io/Game/AI/GameLogic/")
sys.path.append("C:/Users/user/Desktop/Github/hex.github.io/Game/AI/NeuralNetwork/")
from imp import reload
import time
import numpy as np

In [29]:
import GameLogic
reload(GameLogic)
Game = GameLogic.Game

In [92]:
import NeuralNetwork
reload(NeuralNetwork)
NN = NeuralNetwork.NeuralNetwork

In [39]:
import MonteCarloTreeSearch
reload(MonteCarloTreeSearch)
argmax = MonteCarloTreeSearch.argmax
MCTS = MonteCarloTreeSearch.MonteCarloTreeSearch

In [40]:
def one(mcts):
    return mcts.back_prop(mcts.expand_and_eval(mcts.select()))

In [41]:
import threading
class Thread(threading.Thread):
    def __init__(self):
        super().__init__()
        self.stopped = False
    def run(self):
        import playsound
        for i in range(5):
            playsound.playsound("http://ks.imslp.info/files/imglnks/usimg/1/1d/IMSLP84280-PMLP03430-mozart_k305.mp3")
            if self.stopped:
                raise Exception("An error ocurred")
    def RaiseException(self):
        self.stopped = True

In [42]:
game = Game()

In [43]:
mcts = MCTS(game, NN())

Tensor("policy_output_4/Sigmoid:0", shape=(?, 121), dtype=float32)
An error occured while type Checking; parent : None, type(self) : <class 'MonteCarloTreeSearch.MCTS_Node'>


In [44]:
play_game(mcts, game)

0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 132.00329184532166


In [45]:
mcts.train(0.99)

[[[ 1.]
  [-1.]
  [-1.]
  [-1.]
  [-1.]
  [ 1.]
  [ 1.]
  [-1.]
  [ 1.]
  [ 1.]
  [-1.]]

 [[ 1.]
  [-1.]
  [-1.]
  [ 1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]]

 [[-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]]

 [[ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]]

 [[-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]]

 [[ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]]

 [[-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]]

 [[ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]]

 [[-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]]

 [[ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]]

 [[-1.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]]] 1.0 [ 0.  

InvalidArgumentError: Incompatible shapes: [121] vs. [111]
	 [[Node: training_1/SGD/gradients/loss_7/policy_output_loss/mul_1_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _class=["loc:@loss_7/policy_output_loss/mul_1"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](training_1/SGD/gradients/loss_7/policy_output_loss/mul_1_grad/Shape, training_1/SGD/gradients/loss_7/policy_output_loss/mul_1_grad/Shape_1)]]
	 [[Node: loss_7/add/_2863 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_9235_loss_7/add", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'training_1/SGD/gradients/loss_7/policy_output_loss/mul_1_grad/BroadcastGradientArgs', defined at:
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\python\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "c:\python\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "c:\python\lib\site-packages\ipykernel\kernelapp.py", line 478, in start
    self.io_loop.start()
  File "c:\python\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "c:\python\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "c:\python\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\python\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "c:\python\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "c:\python\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "c:\python\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\python\lib\site-packages\ipykernel\kernelbase.py", line 281, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "c:\python\lib\site-packages\ipykernel\kernelbase.py", line 232, in dispatch_shell
    handler(stream, idents, msg)
  File "c:\python\lib\site-packages\ipykernel\kernelbase.py", line 397, in execute_request
    user_expressions, allow_stdin)
  File "c:\python\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "c:\python\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "c:\python\lib\site-packages\IPython\core\interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "c:\python\lib\site-packages\IPython\core\interactiveshell.py", line 2856, in run_ast_nodes
    if self.run_code(code, result):
  File "c:\python\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-45-b559f773debd>", line 1, in <module>
    mcts.train(0.99)
  File "C:/Users/user/Desktop/Github/hex.github.io/Game/AI/TreeSearch\MonteCarloTreeSearch.py", line 224, in train
  File "C:/Users/user/Desktop/Github/hex.github.io/Game/AI/NeuralNetwork\NeuralNetwork.py", line 129, in train_model
    self.model.fit(x=input_data, y={'policy_output':policy_output_data,'value_output':value_output_data}, batch_size=batch_size)
  File "c:\python\lib\site-packages\keras\engine\training.py", line 1634, in fit
    self._make_train_function()
  File "c:\python\lib\site-packages\keras\engine\training.py", line 990, in _make_train_function
    loss=self.total_loss)
  File "c:\python\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "c:\python\lib\site-packages\keras\optimizers.py", line 156, in get_updates
    grads = self.get_gradients(loss, params)
  File "c:\python\lib\site-packages\keras\optimizers.py", line 73, in get_gradients
    grads = K.gradients(loss, params)
  File "c:\python\lib\site-packages\keras\backend\tensorflow_backend.py", line 2394, in gradients
    return tf.gradients(loss, variables, colocate_gradients_with_ops=True)
  File "c:\python\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 581, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "c:\python\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 353, in _MaybeCompile
    return grad_fn()  # Exit early
  File "c:\python\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 581, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "c:\python\lib\site-packages\tensorflow\python\ops\math_grad.py", line 742, in _MulGrad
    rx, ry = gen_array_ops._broadcast_gradient_args(sx, sy)
  File "c:\python\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 531, in _broadcast_gradient_args
    "BroadcastGradientArgs", s0=s0, s1=s1, name=name)
  File "c:\python\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "c:\python\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "c:\python\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'loss_7/policy_output_loss/mul_1', defined at:
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
[elided 20 identical lines from previous traceback]
  File "C:/Users/user/Desktop/Github/hex.github.io/Game/AI/TreeSearch\MonteCarloTreeSearch.py", line 224, in train
  File "C:/Users/user/Desktop/Github/hex.github.io/Game/AI/NeuralNetwork\NeuralNetwork.py", line 128, in train_model
    self.model.compile(loss=loss, optimizer=sgd)
  File "c:\python\lib\site-packages\keras\engine\training.py", line 860, in compile
    sample_weight, mask)
  File "c:\python\lib\site-packages\keras\engine\training.py", line 475, in weighted
    score_array *= weights
  File "c:\python\lib\site-packages\tensorflow\python\ops\math_ops.py", line 894, in binary_op_wrapper
    return func(x, y, name=name)
  File "c:\python\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1117, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "c:\python\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 2725, in _mul
    "Mul", x=x, y=y, name=name)
  File "c:\python\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "c:\python\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "c:\python\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Incompatible shapes: [121] vs. [111]
	 [[Node: training_1/SGD/gradients/loss_7/policy_output_loss/mul_1_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _class=["loc:@loss_7/policy_output_loss/mul_1"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](training_1/SGD/gradients/loss_7/policy_output_loss/mul_1_grad/Shape, training_1/SGD/gradients/loss_7/policy_output_loss/mul_1_grad/Shape_1)]]
	 [[Node: loss_7/add/_2863 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_9235_loss_7/add", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


In [93]:
mcts.batch_processer.model = NN()

Tensor("policy_output_6/Sigmoid:0", shape=(?, 121), dtype=float32)


In [94]:
model = mcts.batch_processer.model

In [95]:
history = mcts.game.history

In [96]:
tData = []

In [97]:
curr_node = mcts.top

In [98]:
for move in history:
    curr_node[move].parent = curr_node
    curr_node = curr_node[move]

In [99]:
curr_node.reward = curr_node.game.GameState

In [100]:
while curr_node.parent:
    tData.append(curr_node.dump())
    curr_node.parent.reward = curr_node.reward * 0.99 * -1
    curr_node = curr_node.parent

In [101]:
pData = [x[1] for x in tData]

In [102]:
vData = [x[2] for x in tData]

In [103]:
iData = [x[0] for x in tData]

In [104]:
i = np.array(iData[0])
p = np.array(pData[0])
v = np.array(vData[0])

In [106]:
i.shape, p.shape, v.shape

((11, 11, 1), (121,), ())

In [110]:
model.train_model(np.expand_dims(i, 0), np.expand_dims(p, 0), np.expand_dims(v, 0))

Epoch 1/1


InvalidArgumentError: slice index 1 of dimension 0 out of bounds.
	 [[Node: loss_14/policy_output_loss/strided_slice_1 = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_policy_output_target_14_0_3/_3719, loss_14/policy_output_loss/strided_slice_3/stack, loss_14/policy_output_loss/strided_slice_3/stack_1, loss_14/policy_output_loss/strided_slice_3/stack)]]
	 [[Node: loss_14/add/_4137 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_9235_loss_14/add", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'loss_14/policy_output_loss/strided_slice_1', defined at:
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\python\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "c:\python\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "c:\python\lib\site-packages\ipykernel\kernelapp.py", line 478, in start
    self.io_loop.start()
  File "c:\python\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "c:\python\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "c:\python\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\python\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "c:\python\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "c:\python\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "c:\python\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\python\lib\site-packages\ipykernel\kernelbase.py", line 281, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "c:\python\lib\site-packages\ipykernel\kernelbase.py", line 232, in dispatch_shell
    handler(stream, idents, msg)
  File "c:\python\lib\site-packages\ipykernel\kernelbase.py", line 397, in execute_request
    user_expressions, allow_stdin)
  File "c:\python\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "c:\python\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "c:\python\lib\site-packages\IPython\core\interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "c:\python\lib\site-packages\IPython\core\interactiveshell.py", line 2856, in run_ast_nodes
    if self.run_code(code, result):
  File "c:\python\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-110-7c1851422027>", line 1, in <module>
    model.train_model(np.expand_dims(i, 0), np.expand_dims(p, 0), np.expand_dims(v, 0))
  File "C:/Users/user/Desktop/Github/hex.github.io/Game/AI/NeuralNetwork\NeuralNetwork.py", line 128, in train_model
    self.model.compile(loss=loss, optimizer=sgd)
  File "c:\python\lib\site-packages\keras\engine\training.py", line 860, in compile
    sample_weight, mask)
  File "c:\python\lib\site-packages\keras\engine\training.py", line 459, in weighted
    score_array = fn(y_true, y_pred)
  File "C:/Users/user/Desktop/Github/hex.github.io/Game/AI/NeuralNetwork\NeuralNetwork.py", line 115, in loss
    p_true, v_true = y_true[0], y_true[1]
  File "c:\python\lib\site-packages\tensorflow\python\ops\array_ops.py", line 538, in _SliceHelper
    name=name)
  File "c:\python\lib\site-packages\tensorflow\python\ops\array_ops.py", line 706, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "c:\python\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 5429, in strided_slice
    name=name)
  File "c:\python\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "c:\python\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "c:\python\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): slice index 1 of dimension 0 out of bounds.
	 [[Node: loss_14/policy_output_loss/strided_slice_1 = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_policy_output_target_14_0_3/_3719, loss_14/policy_output_loss/strided_slice_3/stack, loss_14/policy_output_loss/strided_slice_3/stack_1, loss_14/policy_output_loss/strided_slice_3/stack)]]
	 [[Node: loss_14/add/_4137 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_9235_loss_14/add", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


In [111]:
mcts.train(0.99)

Epoch 1/1


InvalidArgumentError: Incompatible shapes: [121] vs. [111]
	 [[Node: training_3/SGD/gradients/loss_15/policy_output_loss/mul_1_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _class=["loc:@loss_15/policy_output_loss/mul_1"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](training_3/SGD/gradients/loss_15/policy_output_loss/mul_1_grad/Shape, training_3/SGD/gradients/loss_15/policy_output_loss/mul_1_grad/Shape_1)]]
	 [[Node: loss_15/value_output_loss/Mean_2/_4775 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_9239_loss_15/value_output_loss/Mean_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'training_3/SGD/gradients/loss_15/policy_output_loss/mul_1_grad/BroadcastGradientArgs', defined at:
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\python\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "c:\python\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "c:\python\lib\site-packages\ipykernel\kernelapp.py", line 478, in start
    self.io_loop.start()
  File "c:\python\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "c:\python\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "c:\python\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\python\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "c:\python\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "c:\python\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "c:\python\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\python\lib\site-packages\ipykernel\kernelbase.py", line 281, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "c:\python\lib\site-packages\ipykernel\kernelbase.py", line 232, in dispatch_shell
    handler(stream, idents, msg)
  File "c:\python\lib\site-packages\ipykernel\kernelbase.py", line 397, in execute_request
    user_expressions, allow_stdin)
  File "c:\python\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "c:\python\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "c:\python\lib\site-packages\IPython\core\interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "c:\python\lib\site-packages\IPython\core\interactiveshell.py", line 2856, in run_ast_nodes
    if self.run_code(code, result):
  File "c:\python\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-111-b559f773debd>", line 1, in <module>
    mcts.train(0.99)
  File "C:/Users/user/Desktop/Github/hex.github.io/Game/AI/TreeSearch\MonteCarloTreeSearch.py", line 224, in train
  File "C:/Users/user/Desktop/Github/hex.github.io/Game/AI/NeuralNetwork\NeuralNetwork.py", line 129, in train_model
    self.model.fit(x=input_data, y={'policy_output':policy_output_data,'value_output':value_output_data}, batch_size=batch_size)
  File "c:\python\lib\site-packages\keras\engine\training.py", line 1634, in fit
    self._make_train_function()
  File "c:\python\lib\site-packages\keras\engine\training.py", line 990, in _make_train_function
    loss=self.total_loss)
  File "c:\python\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "c:\python\lib\site-packages\keras\optimizers.py", line 156, in get_updates
    grads = self.get_gradients(loss, params)
  File "c:\python\lib\site-packages\keras\optimizers.py", line 73, in get_gradients
    grads = K.gradients(loss, params)
  File "c:\python\lib\site-packages\keras\backend\tensorflow_backend.py", line 2394, in gradients
    return tf.gradients(loss, variables, colocate_gradients_with_ops=True)
  File "c:\python\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 581, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "c:\python\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 353, in _MaybeCompile
    return grad_fn()  # Exit early
  File "c:\python\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 581, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "c:\python\lib\site-packages\tensorflow\python\ops\math_grad.py", line 742, in _MulGrad
    rx, ry = gen_array_ops._broadcast_gradient_args(sx, sy)
  File "c:\python\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 531, in _broadcast_gradient_args
    "BroadcastGradientArgs", s0=s0, s1=s1, name=name)
  File "c:\python\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "c:\python\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "c:\python\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'loss_15/policy_output_loss/mul_1', defined at:
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
[elided 20 identical lines from previous traceback]
  File "C:/Users/user/Desktop/Github/hex.github.io/Game/AI/TreeSearch\MonteCarloTreeSearch.py", line 224, in train
  File "C:/Users/user/Desktop/Github/hex.github.io/Game/AI/NeuralNetwork\NeuralNetwork.py", line 128, in train_model
    self.model.compile(loss=categorical_crossentropy, optimizer=sgd)
  File "c:\python\lib\site-packages\keras\engine\training.py", line 860, in compile
    sample_weight, mask)
  File "c:\python\lib\site-packages\keras\engine\training.py", line 475, in weighted
    score_array *= weights
  File "c:\python\lib\site-packages\tensorflow\python\ops\math_ops.py", line 894, in binary_op_wrapper
    return func(x, y, name=name)
  File "c:\python\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1117, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "c:\python\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 2725, in _mul
    "Mul", x=x, y=y, name=name)
  File "c:\python\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "c:\python\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "c:\python\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Incompatible shapes: [121] vs. [111]
	 [[Node: training_3/SGD/gradients/loss_15/policy_output_loss/mul_1_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _class=["loc:@loss_15/policy_output_loss/mul_1"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](training_3/SGD/gradients/loss_15/policy_output_loss/mul_1_grad/Shape, training_3/SGD/gradients/loss_15/policy_output_loss/mul_1_grad/Shape_1)]]
	 [[Node: loss_15/value_output_loss/Mean_2/_4775 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_9239_loss_15/value_output_loss/Mean_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
