In [1]:
from sys import path
path.append("C:\\Users\\user\\Desktop\\Github\\hex.github.io\\Game\\AI\\")
path.append("C:\\Users\\user\\Desktop\\Github\\hex.github.io\\Dep\\OPTIMISED\\")
path.append("C://Users/user/Desktop/Github/hex.github.io/Game/AI/TreeSearch/")
from imp import reload
import numpy as np

In [2]:
import NeuralNetwork.NeuralNetwork as N_N
reload(N_N)
NN=N_N.NeuralNetwork

Using TensorFlow backend.


In [3]:
model = NN(input_shape=(11,11,1))

In [64]:
import GameLogic.GameLogic as Logic
reload(Logic)
Game = Logic.Game

In [65]:
game = Game()

In [66]:
import TreeSearch.MonteCarloTreeSearch as MonteCarloTreeSearch
reload(MonteCarloTreeSearch)
MCTS = MonteCarloTreeSearch.MonteCarloTreeSearch


In [67]:
tree = MCTS(game, model)

An error


In [68]:
move = tree.turn(10)

<class 'TreeSearch.MonteCarloTreeSearch.MCTS_Node'>, Parent : <class 'NoneType'>, Number of subnodes : 0, expanded : False
[[[ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()